### PR TITLE
Update boss_flame_leviathan.cpp

### PR DESCRIPTION
**Pull request by w5860363**
DELETE FROM `spell_script_names` WHERE `spell_id` IN (64482, 65075, 65076, 65077);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(64482, 'spell_leviathan_tower_buff'),
(65075, 'spell_leviathan_tower_buff'),
(65076, 'spell_leviathan_tower_buff'),
(65077, 'spell_leviathan_tower_buff')

DELETE FROM `spell_script_names` WHERE `spell_id`=62907;
INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
(62907, 'spell_freyas_ward_summon');

### CODE REVIEW

**Comment by M0ra** [comment]
tested script?

**Comment by w5860363** [comment]
@M0ra Is has not completed

**Comment by M0ra** [comment]
spell_vehicle_throw_passenger already used in boss_flame_leviathan.cpp

**Comment by M0ra** [comment]
thanks for PR
keep me updated
https://github.com/M0ra/Core/commit/b45c6d552e554200a99455756f9fb6b257776cb2

**Comment by w5860363** [comment]
@M0ra test https://github.com/M0ra/Core/commit/b45c6d552e554200a99455756f9fb6b257776cb2

mimirons_inferno Not moving but continues to summon

And the direct use of digital will lead to very large number and flame in the sky

**Pull request closed without merging**
